2023-12-21 15:41:51,727 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-21 15:41:51,727 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Configure stats pid to 64439
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Loading settings from /Users/marcinbialek/.config/wandb/settings
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Loading settings from /Users/marcinbialek/PycharmProjects/ai_project_lab/wandb/settings
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/Users/marcinbialek/PycharmProjects/ai_project_lab/main.py', 'program': '/Users/marcinbialek/PycharmProjects/ai_project_lab/main.py'}
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:_log_setup():524] Logging user logs to /Users/marcinbialek/PycharmProjects/ai_project_lab/wandb/run-20231221_154151-zdcsb968/logs/debug.log
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/marcinbialek/PycharmProjects/ai_project_lab/wandb/run-20231221_154151-zdcsb968/logs/debug-internal.log
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:init():564] calling init triggers
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:init():614] starting backend
2023-12-21 15:41:51,728 INFO    MainThread:64439 [wandb_init.py:init():618] setting up manager
2023-12-21 15:41:51,733 INFO    MainThread:64439 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-12-21 15:41:51,735 INFO    MainThread:64439 [wandb_init.py:init():624] backend started and connected
2023-12-21 15:41:51,744 INFO    MainThread:64439 [wandb_init.py:init():716] updated telemetry
2023-12-21 15:41:51,744 INFO    MainThread:64439 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-21 15:42:07,401 ERROR   MainThread:64439 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-21 15:42:08,546 ERROR   MainThread:64439 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/marcinbialek/PycharmProjects/ai_project_lab/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/marcinbialek/PycharmProjects/ai_project_lab/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-21 15:42:09,748 WARNING MsgRouterThr:64439 [router.py:message_loop():77] message_loop has been closed
